apiVersion: apps/v1
kind: Deployment

metadata:
  name: <<name>>-webapi
  namespace: <<application-namespace>>
  labels:
    app: <<name>>-webapi
    run: <<name>>-webapi

spec:
  replicas: 1
  selector:
    matchLabels:
      run: <<name>>-webapi

  template:
    metadata:
      labels:
        app: <<name>>-webapi
        run: <<name>>-webapi

    spec:
      containers:
        - name: <<name>>-webapi
          image: <<your_acr>>.azurecr.io/<<name>>.webapi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Container"

          resources:
            requests:
              cpu: "100m" #50% of a core
              memory: "100Mi"
            limits:
              cpu: "100m" #50% of a core
              memory: "100Mi"
          imagePullPolicy: Always

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
