version: "3.9"

services:
  genocs.webapitemplate.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    networks:
      - genocs
    ports:
      - 80
      - 443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  genocs.webapitemplate.worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
    networks:
      - genocs
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

networks:
  genocs:
    name: genocs-network
    external: true
