version: '3.4'

services:
  genocs.webapitemplate.webapi:
    image: ${DOCKER_REGISTRY-}genocs.webapitemplate.webapi
    build:
      context: .
      dockerfile: webapi.dockerfile

  genocs.webapitemplate.worker:
    image: ${DOCKER_REGISTRY-}genocs.webapitemplate.worker
    build:
      context: .
      dockerfile: worker.dockerfile
