apiVersion: v1
kind: Service

metadata:
  name: {{name}}-service
  namespace: {{application_namespace}}
  labels:
    run: {{name}}-webapi

spec:
  type: ClusterIP

  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 80

  selector:
    run: {{name}}-webapi
